version: 1

consol_log:
  level: INFO

formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  log_handler:
    class: logging.FileHandler
    filename: ml_project.log
    level: INFO
    formatter: simple

  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: simple

loggers:
  src:
    level: INFO
    handlers: [log_handler]
    propagate: yes

root:
  level: INFO
  handlers: [stream_handler]